- name: "Put SELinux in {{ selinux_mode }} mode"
  ansible.posix.selinux:
    policy: targeted
    state: "{{ selinux_mode }}"
  register: selinux_rc

- name: "Reboot"
  ansible.builtin.reboot:
  when: selinux_rc.reboot_required